name: Complex Workflow

on: push

jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print date
        run: date

  job2:
    runs_on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print date
        run: date

  job3:
    runs_on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print date
        run: date
  
  job4:
    runs_on: ubuntu-18.04
    needs: [job1, job2, job3]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print date
        run: date
